site_name: Helping
theme:
  name: material
  palette:
    primary: indigo
    accent: light blue
  font:
    text: EB Garamond
  logo: assets/revolving_hearts.png
  favicon: assets/revolving_hearts.png
nav:
  - Home: index.md
